#### general settings
name: rainL
use_tb_logger: true
model: Rectified_Flow
distortion: derain
gpu_ids: [0]
timesteps_ode: [1]


sde:
  T: 1000
  schedule: linear # linear, cosine


method:
  isXT: True
  base: False
  weighta: 0.3


#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /Datasets/RainL/trainL/GT
    dataroot_LQ: /Datasets/RainL/trainL/LQ

    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 8
    GT_size: 256 #256
    LR_size: 256 #256
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /Datasets/RainL/testL/GT
    dataroot_LQ: /Datasets/RainL/testL/LQ

    batch_size: 1
    # GT_size: 256
    # LR_size: 256
    use_flip: false
    use_rot: false
    color: RGB


# ##### network structures
network_G:
 which_model_G: ConditionalUNet # UNet
 setting:
   in_nc: 3
   out_nc: 3
   nf: 64
   depth: 4


#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  experiments_root: /results


#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR # TrueCosineAnnealingLR # MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l2
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e4


#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
